// <auto-generated />
using System;
using CarRental.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    partial class CarRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("color");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("license_plate");

                    b.Property<Guid>("ModelGenerationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_generation_id");

                    b.HasKey("Id");

                    b.HasIndex("ModelGenerationId");

                    b.ToTable("cars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("14072ffe-8228-458d-85a6-d0dacdac3ba2"),
                            Color = "White",
                            LicensePlate = "A123BC163",
                            ModelGenerationId = new Guid("0c746704-f33f-404f-95b1-38f97182945d")
                        },
                        new
                        {
                            Id = new Guid("68dea793-7fd1-4080-92f4-6099bb83f515"),
                            Color = "Black",
                            LicensePlate = "B456AK163",
                            ModelGenerationId = new Guid("6bbc94b7-ce3e-403c-acc2-7673fcb3b542")
                        },
                        new
                        {
                            Id = new Guid("84d93500-f09b-4e99-8568-cb95b49c5220"),
                            Color = "Gray",
                            LicensePlate = "E789MH163",
                            ModelGenerationId = new Guid("eca5d10e-5e1d-42cc-9ecf-51660ad4eab8")
                        },
                        new
                        {
                            Id = new Guid("c7723367-898d-4497-b0bd-a52e0c98cf7c"),
                            Color = "Red",
                            LicensePlate = "K234OP163",
                            ModelGenerationId = new Guid("6a16941c-23c1-4855-834c-213c9d0c43e0")
                        },
                        new
                        {
                            Id = new Guid("28f97dc8-ac46-440f-914a-4e998dcc7fed"),
                            Color = "Silver",
                            LicensePlate = "M567TX163",
                            ModelGenerationId = new Guid("8d40cbfb-f7d1-4c37-a9a3-2a83cfe4b68e")
                        },
                        new
                        {
                            Id = new Guid("ca24e7de-2c58-4fb0-bd82-2d8954305329"),
                            Color = "Blue",
                            LicensePlate = "P890CH163",
                            ModelGenerationId = new Guid("6a2500b4-5c0d-475e-9091-57f1f5eebd5e")
                        },
                        new
                        {
                            Id = new Guid("07a51db0-5a9c-4d22-ac23-0d38d5058382"),
                            Color = "White",
                            LicensePlate = "C345EA163",
                            ModelGenerationId = new Guid("5555399c-0d61-4282-a9a8-8ec62c779c0a")
                        },
                        new
                        {
                            Id = new Guid("63e52545-fffe-4bc4-bc23-6b00f29b255b"),
                            Color = "Black",
                            LicensePlate = "T678HX163",
                            ModelGenerationId = new Guid("e71fad6a-7130-4ec8-9c54-4cd9377a9f3e")
                        },
                        new
                        {
                            Id = new Guid("ba69ea51-36be-44d5-9140-bba02b84270e"),
                            Color = "Gray",
                            LicensePlate = "O901KP163",
                            ModelGenerationId = new Guid("16148b60-652c-4a4f-bea5-08b04036db05")
                        },
                        new
                        {
                            Id = new Guid("e8432c42-312b-438b-b446-319670e7a5a8"),
                            Color = "Red",
                            LicensePlate = "H112ME163",
                            ModelGenerationId = new Guid("f3e00c4c-9688-4aa4-860e-4f82c922c001")
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("driver_license_number");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44c818d9-546b-45ed-ba31-bc8f11bc4555"),
                            BirthDate = new DateOnly(2003, 4, 21),
                            DriverLicenseNumber = "6314123456",
                            FullName = "Roman Ivanov"
                        },
                        new
                        {
                            Id = new Guid("42927043-7438-4a6a-8706-a5fd251550ef"),
                            BirthDate = new DateOnly(2004, 8, 15),
                            DriverLicenseNumber = "7707654321",
                            FullName = "Marina Smirnova"
                        },
                        new
                        {
                            Id = new Guid("8402de35-2ea9-4f95-af14-eb99c2a14992"),
                            BirthDate = new DateOnly(1998, 3, 3),
                            DriverLicenseNumber = "7809234567",
                            FullName = "Alex Petrov"
                        },
                        new
                        {
                            Id = new Guid("00254aaa-193e-4eab-90f0-9d830866ce95"),
                            BirthDate = new DateOnly(1990, 1, 5),
                            DriverLicenseNumber = "5011345678",
                            FullName = "Sergey Karpov"
                        },
                        new
                        {
                            Id = new Guid("2c707871-8d93-4fc2-9bd0-a0691abe2419"),
                            BirthDate = new DateOnly(1988, 11, 28),
                            DriverLicenseNumber = "1610987654",
                            FullName = "Olga Kuznetsova"
                        },
                        new
                        {
                            Id = new Guid("525c380f-ba84-4571-80ef-9aab2049f75c"),
                            BirthDate = new DateOnly(1999, 9, 12),
                            DriverLicenseNumber = "6412112233",
                            FullName = "Nikita Sidorov"
                        },
                        new
                        {
                            Id = new Guid("38bef19b-0bdc-478c-b15c-81ccfc63d0a1"),
                            BirthDate = new DateOnly(1985, 5, 2),
                            DriverLicenseNumber = "5413445566",
                            FullName = "Pavel Orlov"
                        },
                        new
                        {
                            Id = new Guid("d88a9c6a-2424-4865-b43b-fab9eb948c8f"),
                            BirthDate = new DateOnly(2001, 6, 22),
                            DriverLicenseNumber = "3608778899",
                            FullName = "Anna Volkova"
                        },
                        new
                        {
                            Id = new Guid("030774ea-647c-4039-8e68-21536e83a93d"),
                            BirthDate = new DateOnly(1994, 7, 9),
                            DriverLicenseNumber = "7704556677",
                            FullName = "Ivan Belov"
                        },
                        new
                        {
                            Id = new Guid("4ef2250c-0d70-4c39-8b17-102773c1b153"),
                            BirthDate = new DateOnly(1992, 12, 31),
                            DriverLicenseNumber = "7815990011",
                            FullName = "Elena Sergeeva"
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("BodyCarType")
                        .HasColumnType("int")
                        .HasColumnName("body_car_type");

                    b.Property<int>("ClassCar")
                        .HasColumnType("int")
                        .HasColumnName("class_car");

                    b.Property<string>("NameModel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int")
                        .HasColumnName("seat_number");

                    b.Property<int>("TypeDrive")
                        .HasColumnType("int")
                        .HasColumnName("type_drive");

                    b.HasKey("Id");

                    b.ToTable("models", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba35b213-664d-48b4-8941-c8605bd597b5"),
                            BodyCarType = 0,
                            ClassCar = 3,
                            NameModel = "Toyota Camry",
                            SeatNumber = 5,
                            TypeDrive = 0
                        },
                        new
                        {
                            Id = new Guid("6e047d30-3427-49ba-b8fa-620b507fcf34"),
                            BodyCarType = 0,
                            ClassCar = 3,
                            NameModel = "BMW 3 Series",
                            SeatNumber = 5,
                            TypeDrive = 1
                        },
                        new
                        {
                            Id = new Guid("453a6ecb-8a97-4e38-a025-d4eb1512a914"),
                            BodyCarType = 3,
                            ClassCar = 4,
                            NameModel = "Audi Q5",
                            SeatNumber = 5,
                            TypeDrive = 2
                        },
                        new
                        {
                            Id = new Guid("be2590ff-9565-4388-80b8-ce542f7a5c26"),
                            BodyCarType = 1,
                            ClassCar = 2,
                            NameModel = "Volkswagen Golf",
                            SeatNumber = 5,
                            TypeDrive = 0
                        },
                        new
                        {
                            Id = new Guid("9a01902a-c45f-4899-a616-c7e859cae37f"),
                            BodyCarType = 0,
                            ClassCar = 4,
                            NameModel = "Mercedes C-Class",
                            SeatNumber = 5,
                            TypeDrive = 1
                        },
                        new
                        {
                            Id = new Guid("27663e74-ffcb-4bb6-8615-6c728b223e1a"),
                            BodyCarType = 3,
                            ClassCar = 2,
                            NameModel = "Hyundai Tucson",
                            SeatNumber = 5,
                            TypeDrive = 2
                        },
                        new
                        {
                            Id = new Guid("e4843b94-5913-4fe6-9067-908576262d28"),
                            BodyCarType = 0,
                            ClassCar = 1,
                            NameModel = "Kia Rio",
                            SeatNumber = 5,
                            TypeDrive = 0
                        },
                        new
                        {
                            Id = new Guid("9f5c3f00-1fa3-444d-bdd3-b6aff14a6615"),
                            BodyCarType = 1,
                            ClassCar = 2,
                            NameModel = "Ford Focus",
                            SeatNumber = 5,
                            TypeDrive = 0
                        },
                        new
                        {
                            Id = new Guid("74190ed9-6fba-4225-9ba9-3c2037fbc5c0"),
                            BodyCarType = 3,
                            ClassCar = 3,
                            NameModel = "Nissan X-Trail",
                            SeatNumber = 5,
                            TypeDrive = 2
                        },
                        new
                        {
                            Id = new Guid("c4c83b9d-9f1d-47bf-95e1-c762682b139a"),
                            BodyCarType = 0,
                            ClassCar = 2,
                            NameModel = "Lada Vesta",
                            SeatNumber = 5,
                            TypeDrive = 0
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.ModelGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<double>("EngineCapacity")
                        .HasColumnType("double")
                        .HasColumnName("engine_capacity");

                    b.Property<int>("GearBoxType")
                        .HasColumnType("int")
                        .HasColumnName("gear_box_type");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_id");

                    b.Property<decimal>("RentalPricePerHour")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("rental_price_per_hour");

                    b.Property<int>("YearManufacture")
                        .HasColumnType("int")
                        .HasColumnName("year_manufacture");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("model_generations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c746704-f33f-404f-95b1-38f97182945d"),
                            EngineCapacity = 2.5,
                            GearBoxType = 1,
                            ModelId = new Guid("ba35b213-664d-48b4-8941-c8605bd597b5"),
                            RentalPricePerHour = 10.0m,
                            YearManufacture = 2020
                        },
                        new
                        {
                            Id = new Guid("6bbc94b7-ce3e-403c-acc2-7673fcb3b542"),
                            EngineCapacity = 2.0,
                            GearBoxType = 1,
                            ModelId = new Guid("6e047d30-3427-49ba-b8fa-620b507fcf34"),
                            RentalPricePerHour = 13.0m,
                            YearManufacture = 2022
                        },
                        new
                        {
                            Id = new Guid("eca5d10e-5e1d-42cc-9ecf-51660ad4eab8"),
                            EngineCapacity = 2.0,
                            GearBoxType = 3,
                            ModelId = new Guid("453a6ecb-8a97-4e38-a025-d4eb1512a914"),
                            RentalPricePerHour = 15.0m,
                            YearManufacture = 2021
                        },
                        new
                        {
                            Id = new Guid("6a16941c-23c1-4855-834c-213c9d0c43e0"),
                            EngineCapacity = 1.3999999999999999,
                            GearBoxType = 0,
                            ModelId = new Guid("be2590ff-9565-4388-80b8-ce542f7a5c26"),
                            RentalPricePerHour = 7.0m,
                            YearManufacture = 2019
                        },
                        new
                        {
                            Id = new Guid("8d40cbfb-f7d1-4c37-a9a3-2a83cfe4b68e"),
                            EngineCapacity = 2.0,
                            GearBoxType = 1,
                            ModelId = new Guid("9a01902a-c45f-4899-a616-c7e859cae37f"),
                            RentalPricePerHour = 16.5m,
                            YearManufacture = 2023
                        },
                        new
                        {
                            Id = new Guid("6a2500b4-5c0d-475e-9091-57f1f5eebd5e"),
                            EngineCapacity = 2.0,
                            GearBoxType = 2,
                            ModelId = new Guid("27663e74-ffcb-4bb6-8615-6c728b223e1a"),
                            RentalPricePerHour = 12.0m,
                            YearManufacture = 2022
                        },
                        new
                        {
                            Id = new Guid("5555399c-0d61-4282-a9a8-8ec62c779c0a"),
                            EngineCapacity = 1.6000000000000001,
                            GearBoxType = 1,
                            ModelId = new Guid("e4843b94-5913-4fe6-9067-908576262d28"),
                            RentalPricePerHour = 6.5m,
                            YearManufacture = 2020
                        },
                        new
                        {
                            Id = new Guid("e71fad6a-7130-4ec8-9c54-4cd9377a9f3e"),
                            EngineCapacity = 1.5,
                            GearBoxType = 0,
                            ModelId = new Guid("9f5c3f00-1fa3-444d-bdd3-b6aff14a6615"),
                            RentalPricePerHour = 8.0m,
                            YearManufacture = 2021
                        },
                        new
                        {
                            Id = new Guid("16148b60-652c-4a4f-bea5-08b04036db05"),
                            EngineCapacity = 2.5,
                            GearBoxType = 1,
                            ModelId = new Guid("74190ed9-6fba-4225-9ba9-3c2037fbc5c0"),
                            RentalPricePerHour = 14.0m,
                            YearManufacture = 2022
                        },
                        new
                        {
                            Id = new Guid("f3e00c4c-9688-4aa4-860e-4f82c922c001"),
                            EngineCapacity = 1.6000000000000001,
                            GearBoxType = 0,
                            ModelId = new Guid("c4c83b9d-9f1d-47bf-95e1-c762682b139a"),
                            RentalPricePerHour = 5.5m,
                            YearManufacture = 2021
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("char(36)")
                        .HasColumnName("car_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)")
                        .HasColumnName("client_id");

                    b.Property<double>("RentalDurationHours")
                        .HasColumnType("double")
                        .HasColumnName("rental_duration_hours");

                    b.Property<DateTime>("RentalStartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("rental_start_time");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("rentals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d4bda3f-bc8a-405d-8e04-c65fa5bb41d8"),
                            CarId = new Guid("14072ffe-8228-458d-85a6-d0dacdac3ba2"),
                            ClientId = new Guid("44c818d9-546b-45ed-ba31-bc8f11bc4555"),
                            RentalDurationHours = 4.0,
                            RentalStartTime = new DateTime(2025, 11, 26, 6, 25, 18, 125, DateTimeKind.Local).AddTicks(4656)
                        },
                        new
                        {
                            Id = new Guid("fe1fc6bc-7c3f-4a84-9484-39c0a8d30c87"),
                            CarId = new Guid("68dea793-7fd1-4080-92f4-6099bb83f515"),
                            ClientId = new Guid("42927043-7438-4a6a-8706-a5fd251550ef"),
                            RentalDurationHours = 3.0,
                            RentalStartTime = new DateTime(2025, 11, 25, 16, 25, 18, 125, DateTimeKind.Local).AddTicks(4910)
                        },
                        new
                        {
                            Id = new Guid("13bdb3bb-9483-405a-9658-e1276378a0b8"),
                            CarId = new Guid("84d93500-f09b-4e99-8568-cb95b49c5220"),
                            ClientId = new Guid("8402de35-2ea9-4f95-af14-eb99c2a14992"),
                            RentalDurationHours = 6.0,
                            RentalStartTime = new DateTime(2025, 11, 24, 16, 25, 18, 125, DateTimeKind.Local).AddTicks(4921)
                        },
                        new
                        {
                            Id = new Guid("1cdaafad-08af-424d-9697-1ba21a45e2b5"),
                            CarId = new Guid("c7723367-898d-4497-b0bd-a52e0c98cf7c"),
                            ClientId = new Guid("00254aaa-193e-4eab-90f0-9d830866ce95"),
                            RentalDurationHours = 2.0,
                            RentalStartTime = new DateTime(2025, 11, 23, 16, 25, 18, 125, DateTimeKind.Local).AddTicks(4922)
                        },
                        new
                        {
                            Id = new Guid("311464f2-da86-40ea-8bb4-eee6079aec03"),
                            CarId = new Guid("28f97dc8-ac46-440f-914a-4e998dcc7fed"),
                            ClientId = new Guid("2c707871-8d93-4fc2-9bd0-a0691abe2419"),
                            RentalDurationHours = 8.0,
                            RentalStartTime = new DateTime(2025, 11, 22, 16, 25, 18, 125, DateTimeKind.Local).AddTicks(4924)
                        },
                        new
                        {
                            Id = new Guid("d5dae61f-e874-4fe4-a9c1-08556ead27a4"),
                            CarId = new Guid("ca24e7de-2c58-4fb0-bd82-2d8954305329"),
                            ClientId = new Guid("525c380f-ba84-4571-80ef-9aab2049f75c"),
                            RentalDurationHours = 5.0,
                            RentalStartTime = new DateTime(2025, 11, 21, 16, 25, 18, 125, DateTimeKind.Local).AddTicks(4925)
                        },
                        new
                        {
                            Id = new Guid("e6519f4a-7599-4ce8-bac9-c31c55244fbd"),
                            CarId = new Guid("07a51db0-5a9c-4d22-ac23-0d38d5058382"),
                            ClientId = new Guid("38bef19b-0bdc-478c-b15c-81ccfc63d0a1"),
                            RentalDurationHours = 3.0,
                            RentalStartTime = new DateTime(2025, 11, 20, 16, 25, 18, 125, DateTimeKind.Local).AddTicks(4926)
                        },
                        new
                        {
                            Id = new Guid("6ed229cd-e258-4d2a-8b9a-f2eeaf5d6f19"),
                            CarId = new Guid("63e52545-fffe-4bc4-bc23-6b00f29b255b"),
                            ClientId = new Guid("d88a9c6a-2424-4865-b43b-fab9eb948c8f"),
                            RentalDurationHours = 2.0,
                            RentalStartTime = new DateTime(2025, 11, 19, 16, 25, 18, 125, DateTimeKind.Local).AddTicks(4931)
                        },
                        new
                        {
                            Id = new Guid("7cf99400-ca41-4b1a-a2cc-a8e8ab0d0248"),
                            CarId = new Guid("ba69ea51-36be-44d5-9140-bba02b84270e"),
                            ClientId = new Guid("030774ea-647c-4039-8e68-21536e83a93d"),
                            RentalDurationHours = 4.0,
                            RentalStartTime = new DateTime(2025, 11, 18, 16, 25, 18, 125, DateTimeKind.Local).AddTicks(4933)
                        },
                        new
                        {
                            Id = new Guid("fe0145db-50f8-4a32-82ff-ea91859aa71b"),
                            CarId = new Guid("e8432c42-312b-438b-b446-319670e7a5a8"),
                            ClientId = new Guid("4ef2250c-0d70-4c39-8b17-102773c1b153"),
                            RentalDurationHours = 7.0,
                            RentalStartTime = new DateTime(2025, 11, 17, 16, 25, 18, 125, DateTimeKind.Local).AddTicks(4934)
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Car", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.ModelGeneration", "ModelGeneration")
                        .WithMany()
                        .HasForeignKey("ModelGenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelGeneration");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.ModelGeneration", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
